version: 2

updates:
  - package-ecosystem: gomod
    directories:
      - "/"
      - "/examples"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      go-dependencies:
        applies-to: version-updates
        group-by: dependency-name
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - no-changelog
