package jpl_test

import "github.com/TuSKan/astrogo/time"

// fixedEpoch is the instant tests use when they need *an* epoch rather than a
// particular one.
//
// See coord's copy for the full reasoning. For a kernel-backed provider there
// is a second drift on top of the EOP one: an SPK covers a finite span, and a
// test at "now" walks toward the end of it. de440s reaches 2150 so that is not
// the near-term risk, but a small-body kernel generated by Horizons covers far
// less, and the failure would look identical.
//
// 2024-06-15 is inside measured EOP coverage, inside every kernel this package
// loads, and away from any leap second.
func fixedEpoch() time.Time {
	return time.Date(2024, time.June, 15, 12, 0, 0, 0, time.LocationUTC)
}
