version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true
