run:
  # Bypass golangci-lint version panic on new Go versions natively
  go: "1.24"

linters:
  # Enable specific linters
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  gofmt:
    # Simplify code: gofmt with `-s` option
    simplify: true
