package constellation

// names maps each catalog abbreviation (as used in rawBoundary) to the
// constellation's standard IAU 3-letter abbreviation and full name.
// "SER1"/"SER2" (Serpens Caput and Serpens Cauda — the catalog's two
// disconnected regions for the one constellation Ophiuchus splits in two)
// both map to "Serpens"/"Ser".
var names = map[string]struct{ abbr, full string }{
	"AND":  {"And", "Andromeda"},
	"ANT":  {"Ant", "Antlia"},
	"APS":  {"Aps", "Apus"},
	"AQL":  {"Aql", "Aquila"},
	"AQR":  {"Aqr", "Aquarius"},
	"ARA":  {"Ara", "Ara"},
	"ARI":  {"Ari", "Aries"},
	"AUR":  {"Aur", "Auriga"},
	"BOO":  {"Boo", "Boötes"},
	"CAE":  {"Cae", "Caelum"},
	"CAM":  {"Cam", "Camelopardalis"},
	"CAP":  {"Cap", "Capricornus"},
	"CAR":  {"Car", "Carina"},
	"CAS":  {"Cas", "Cassiopeia"},
	"CEN":  {"Cen", "Centaurus"},
	"CEP":  {"Cep", "Cepheus"},
	"CET":  {"Cet", "Cetus"},
	"CHA":  {"Cha", "Chamaeleon"},
	"CIR":  {"Cir", "Circinus"},
	"CMA":  {"CMa", "Canis Major"},
	"CMI":  {"CMi", "Canis Minor"},
	"CNC":  {"Cnc", "Cancer"},
	"COL":  {"Col", "Columba"},
	"COM":  {"Com", "Coma Berenices"},
	"CRA":  {"CrA", "Corona Australis"},
	"CRB":  {"CrB", "Corona Borealis"},
	"CRT":  {"Crt", "Crater"},
	"CRU":  {"Cru", "Crux"},
	"CRV":  {"Crv", "Corvus"},
	"CVN":  {"CVn", "Canes Venatici"},
	"CYG":  {"Cyg", "Cygnus"},
	"DEL":  {"Del", "Delphinus"},
	"DOR":  {"Dor", "Dorado"},
	"DRA":  {"Dra", "Draco"},
	"EQU":  {"Equ", "Equuleus"},
	"ERI":  {"Eri", "Eridanus"},
	"FOR":  {"For", "Fornax"},
	"GEM":  {"Gem", "Gemini"},
	"GRU":  {"Gru", "Grus"},
	"HER":  {"Her", "Hercules"},
	"HOR":  {"Hor", "Horologium"},
	"HYA":  {"Hya", "Hydra"},
	"HYI":  {"Hyi", "Hydrus"},
	"IND":  {"Ind", "Indus"},
	"LAC":  {"Lac", "Lacerta"},
	"LEO":  {"Leo", "Leo"},
	"LEP":  {"Lep", "Lepus"},
	"LIB":  {"Lib", "Libra"},
	"LMI":  {"LMi", "Leo Minor"},
	"LUP":  {"Lup", "Lupus"},
	"LYN":  {"Lyn", "Lynx"},
	"LYR":  {"Lyr", "Lyra"},
	"MEN":  {"Men", "Mensa"},
	"MIC":  {"Mic", "Microscopium"},
	"MON":  {"Mon", "Monoceros"},
	"MUS":  {"Mus", "Musca"},
	"NOR":  {"Nor", "Norma"},
	"OCT":  {"Oct", "Octans"},
	"OPH":  {"Oph", "Ophiuchus"},
	"ORI":  {"Ori", "Orion"},
	"PAV":  {"Pav", "Pavo"},
	"PEG":  {"Peg", "Pegasus"},
	"PER":  {"Per", "Perseus"},
	"PHE":  {"Phe", "Phoenix"},
	"PIC":  {"Pic", "Pictor"},
	"PSA":  {"PsA", "Piscis Austrinus"},
	"PSC":  {"Psc", "Pisces"},
	"PUP":  {"Pup", "Puppis"},
	"PYX":  {"Pyx", "Pyxis"},
	"RET":  {"Ret", "Reticulum"},
	"SCL":  {"Scl", "Sculptor"},
	"SCO":  {"Sco", "Scorpius"},
	"SCT":  {"Sct", "Scutum"},
	"SER1": {"Ser", "Serpens"},
	"SER2": {"Ser", "Serpens"},
	"SEX":  {"Sex", "Sextans"},
	"SGE":  {"Sge", "Sagitta"},
	"SGR":  {"Sgr", "Sagittarius"},
	"TAU":  {"Tau", "Taurus"},
	"TEL":  {"Tel", "Telescopium"},
	"TRI":  {"Tri", "Triangulum"},
	"TRA":  {"TrA", "Triangulum Australe"},
	"TUC":  {"Tuc", "Tucana"},
	"UMA":  {"UMa", "Ursa Major"},
	"UMI":  {"UMi", "Ursa Minor"},
	"VEL":  {"Vel", "Vela"},
	"VIR":  {"Vir", "Virgo"},
	"VOL":  {"Vol", "Volans"},
	"VUL":  {"Vul", "Vulpecula"},
}
