package coord_test

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/TuSKan/astrogo/angle"
	"github.com/TuSKan/astrogo/atmosphere"
	"github.com/TuSKan/astrogo/coord"
	"github.com/TuSKan/astrogo/internal/metrology"
	"github.com/TuSKan/astrogo/time"
)

// rvFixturePath is the checked-in Astropy reference table.
const rvFixturePath = "testdata/rv_astropy.json"

// rvFixtureSchemaVersion is the layout this reader understands. Checked on
// read and never guessed at, for the same reason the Horizons corpus checks
// its own: reinterpreting an older layout compares two things that were not
// measured the same way.
const rvFixtureSchemaVersion = 1

// rvFixture is the whole reference document.
//
// It replaced a hand-written Go slice that was never filled in. The scaffold
// said, correctly, that fabricating placeholder numbers would validate
// nothing while looking like it did — so it skipped, and went on skipping,
// and docs/VALIDATION.md carried no row for a public function at all. The
// values below are real Astropy 8.0.1 output, regenerated by
// testdata/rvfixture/generate.py.
type rvFixture struct {
	SchemaVersion int    `json:"schema_version"`
	Generated     string `json:"generated"`
	AstrogoCommit string `json:"astrogo_commit"`

	Generator struct {
		Astropy string `json:"astropy"`
		PyERFA  string `json:"pyerfa"`
		NumPy   string `json:"numpy"`
		Python  string `json:"python"`
	} `json:"generator"`

	BarycentricNote string `json:"barycentric_note"`
	Convention      string `json:"convention"`
	SharedAncestry  string `json:"shared_ancestry"`

	Cases []rvFixtureCase `json:"cases"`
}

// rvFixtureCase is one (site, epoch, target) triple and the corrections
// Astropy computes for it, in km/s.
type rvFixtureCase struct {
	Name string `json:"name"`

	Site struct {
		Name    string  `json:"name"`
		Lon     float64 `json:"lon_deg"`
		Lat     float64 `json:"lat_deg"`
		HeightM float64 `json:"height_m"`
	} `json:"site"`

	EpochUTC  string `json:"epoch_utc"`
	EpochNote string `json:"epoch_note"`

	Target struct {
		Name string  `json:"name"`
		RA   float64 `json:"ra_deg"`
		Dec  float64 `json:"dec_deg"`
	} `json:"target"`

	// Barycentric is Astropy's full value, which is relativistic.
	// BarycentricClassical is the plain projection of the same observer
	// velocity onto the same line of sight — the model astrogo implements.
	// See BarycentricNote on the document.
	Barycentric          float64 `json:"barycentric_km_s"`
	BarycentricClassical float64 `json:"barycentric_classical_km_s"`
	Heliocentric         float64 `json:"heliocentric_km_s"`
}

func loadRVFixture(t *testing.T) rvFixture {
	t.Helper()

	data, err := os.ReadFile(filepath.Clean(rvFixturePath))
	if err != nil {
		t.Fatalf("reading %s: %v\n  regenerate with: cd coord/testdata/rvfixture && uv run generate.py",
			rvFixturePath, err)
	}

	var f rvFixture
	if err := json.Unmarshal(data, &f); err != nil {
		t.Fatalf("decoding %s: %v", rvFixturePath, err)
	}

	if f.SchemaVersion != rvFixtureSchemaVersion {
		t.Fatalf("%s is schema version %d, this reader understands %d",
			rvFixturePath, f.SchemaVersion, rvFixtureSchemaVersion)
	}

	if len(f.Cases) == 0 {
		t.Fatalf("%s carries no cases", rvFixturePath)
	}

	return f
}

// TestRVCorrectionAgainstAstropy cross-checks BarycentricRVCorrection and
// HeliocentricRVCorrection against real Astropy output.
//
// # What this adds over the invariant tests beside it
//
// Those check identities: an annual sinusoid of the right amplitude, zero for
// a target perpendicular to the velocity, a sign flip for antipodal targets, a
// diurnal amplitude scaling as cos(latitude), a round trip through
// ObservedRadialVelocity. They are strong and they share one blind spot — an
// identity cannot catch an error both of its sides make. A projection with the
// wrong sign convention still flips sign for antipodal targets; one that
// dropped the diurnal term entirely still produces an annual sinusoid.
//
// # What it does not add, which matters more
//
// Astropy reaches the observer's barycentric velocity through pyerfa and
// astrogo reaches it through gofa. Both are SOFA-derived and both arrive by
// the same epv00 algorithm, so this is **not** an independent check of the
// Earth ephemeris and the suite records that rather than claiming otherwise.
// What it does check is everything astrogo puts around that shared core: the
// projection onto the line of sight, the sign convention, the site geodesy,
// the time-scale handling, and the heliocentric-minus-barycentric difference.
// Those are where the errors in an RV correction actually live, and the shared
// part is separately checked against DE440 by ephemeris.sofa.sun.
//
// # The contract
//
// astrogo documents about 1 m/s accuracy and says plainly it is a classical
// projection: no gravitational redshift, no light-travel time to the
// barycentre, no proper-motion or parallax effect on the projection geometry —
// the Wright & Eastman (2014) terms. Astropy's own documentation puts its
// barycentric correction at roughly 3 m/s against a full precision-RV code.
// Two classical implementations agreeing should therefore sit near the
// arithmetic noise of the shared ephemeris rather than near either accuracy
// claim, and the bound is set at 1 m/s: below astrogo's own stated accuracy,
// so it cannot be met by an implementation that has quietly stopped being as
// good as it claims, and far above float64 projection noise.
func TestRVCorrectionAgainstAstropy(t *testing.T) {
	t.Parallel()

	fixture := loadRVFixture(t)

	t.Logf("fixture: %d cases, generated %s at astrogo %s",
		len(fixture.Cases), fixture.Generated, fixture.AstrogoCommit)
	t.Logf("  astropy %s, pyerfa %s, numpy %s, python %s",
		fixture.Generator.Astropy, fixture.Generator.PyERFA,
		fixture.Generator.NumPy, fixture.Generator.Python)
	t.Logf("  convention: %s", fixture.Convention)
	t.Logf("  shared ancestry: %s", fixture.SharedAncestry)
	t.Logf("  barycentric: %s", fixture.BarycentricNote)

	ref := metrology.Reference{
		Kind:    metrology.KindImplementation,
		Name:    "Astropy SkyCoord.radial_velocity_correction",
		Version: fixture.Generator.Astropy,
		Source:  "coord/testdata/rvfixture/generate.py",
		Dataset: "testdata/rv_astropy.json, generated " + fixture.Generated,

		// Both sides reach the observer's barycentric velocity by SOFA's
		// epv00 — Astropy through pyerfa, astrogo through gofa. The
		// projection around it is independent; the ephemeris under it is not.
		SharedAncestor: "SOFA/ERFA epv00",
	}

	contract := metrology.MustContract(1e-3, "km/s",
		"1 m/s, below astrogo's own stated accuracy for this classical projection and far "+
			"above float64 noise; two classical implementations sharing an ephemeris should "+
			"differ only in the projection, and a disagreement above this is a sign convention, "+
			"a site position or a time scale rather than a modelling difference",
		"coord/radialvelocity.go's accuracy note; Wright & Eastman (2014) for the terms neither side models")

	// The two suites report identical residual distributions, and that is
	// physics rather than a copy-paste.
	//
	// The heliocentric correction differs from the barycentric one by the
	// Sun's own barycentric velocity, which both implementations derive from
	// the same epv00 call — Astropy directly, astrogo as
	// Earth_bary - Earth_helio. Measured, the two sides agree on that
	// difference to the last printed digit (0.012412171 km/s at Greenwich on
	// 2026-01-04, both), so it cancels exactly out of the residual and what
	// is left is the same observer-velocity noise in both.
	//
	// They are still separate suites because they exercise separate code:
	// HeliocentricRVCorrection calls Epv00 afresh and does its own
	// subtraction, so a defect there would move this residual and not the
	// other one.
	bary := metrology.NewSuite("coord.rv.barycentric", ref, contract)
	helio := metrology.NewSuite("coord.rv.heliocentric", ref, contract)

	relativistic := make([]float64, 0, len(fixture.Cases))

	// Pressure zero disables refraction, which has no bearing on a velocity
	// projection and would otherwise be one more thing differing between the
	// two implementations.
	atm := atmosphere.Refraction{Pressure: 0}

	for _, tc := range fixture.Cases {
		site, err := coord.NewGeodetic(
			angle.Deg(tc.Site.Lon), angle.Deg(tc.Site.Lat), tc.Site.HeightM)
		if err != nil {
			t.Fatalf("%s: %v", tc.Name, err)
		}

		parsed, err := time.Parse(time.RFC3339, tc.EpochUTC+"Z")
		if err != nil {
			t.Fatalf("%s: parsing %q: %v", tc.Name, tc.EpochUTC, err)
		}

		ctx := coord.NewContext(time.FromGo(parsed), site, atm)
		target := coord.NewICRS(angle.Deg(tc.Target.RA), angle.Deg(tc.Target.Dec))

		gotHelio, err := ctx.HeliocentricRVCorrection(target)
		if err != nil {
			t.Fatalf("%s: HeliocentricRVCorrection: %v", tc.Name, err)
		}

		context := tc.EpochUTC + " (" + tc.EpochNote + ")"

		// Signed, so a convention mismatch shows as every case leaning one
		// way rather than as scatter.
		got := ctx.BarycentricRVCorrection(target)

		bary.Add(metrology.Sample{
			Error:   got - tc.BarycentricClassical,
			Label:   tc.Name,
			Context: context,
		})

		// The relativistic gap is recorded, not asserted: it is a stated
		// difference between the two models rather than an error in either.
		relativistic = append(relativistic, tc.Barycentric-got)

		helio.Add(metrology.Sample{
			Error:   gotHelio - tc.Heliocentric,
			Label:   tc.Name,
			Context: context,
		})
	}

	bary.Report(t)
	helio.Report(t)

	// Report the model difference explicitly, and check it is the size the
	// physics says it should be.
	//
	// astrogo is classical by design; Astropy's barycentric branch is not.
	// The gap should be the terms astrogo documents itself as omitting —
	// second-order Doppler v^2/2c at 1.48 m/s, the Sun's gravitational
	// redshift GM/rc at 2.96, and Earth's own at 0.21, summing to 4.65 m/s.
	// Asserting the size of a known difference is worth more than ignoring
	// it: if the two implementations ever diverge for some *other* reason,
	// this number moves and says so.
	sort.Float64s(relativistic)

	const (
		predictedRelativistic = 4.649e-3 // km/s
		relativisticTolerance = 0.5e-3   // km/s
	)

	median := metrology.Quantile(relativistic, 0.5)

	t.Logf("relativistic gap, Astropy barycentric minus astrogo classical: "+
		"n=%d p50=%.4f p95=%.4f max=%.4f m/s",
		len(relativistic), median*1e3,
		metrology.Quantile(relativistic, 0.95)*1e3,
		metrology.Quantile(relativistic, 1.0)*1e3)
	t.Logf("  predicted %.3f m/s = second-order Doppler 1.481 + solar redshift 2.959 + "+
		"Earth redshift 0.209", predictedRelativistic*1e3)

	if math.Abs(median-predictedRelativistic) > relativisticTolerance {
		t.Errorf("the gap between Astropy's relativistic barycentric correction and astrogo's "+
			"classical one is %.4f m/s, but the terms astrogo documents as omitted predict "+
			"%.4f m/s. Either astrogo has acquired a defect the classical comparison above "+
			"cannot see, or Astropy has changed its model.",
			median*1e3, predictedRelativistic*1e3)
	}
}
