package sgp4_test

import (
	"bufio"
	"errors"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/TuSKan/astrogo/ephemeris/satellite/sgp4"
)

// This file measures the model against the reference states Vallado published
// with AIAA 2006-6753. See ../testdata/vallado/README.md for provenance.
//
// It is untagged, unlike astrogo's other validation suites, and deliberately:
// the fixture is 30 KB on disk, the comparison is a few hundred thousand
// floating-point operations, and there is no network and no external service
// anywhere in it. A correctness claim this cheap to check should be checked on
// every run.

// valladoMaxKM is the contract: 0.1 mm.
//
// Not a statement about where satellites are — SGP4's own model error is
// kilometers within days of epoch. A statement about whether this is the same
// arithmetic as the reference.
//
// # Where the number comes from
//
// tcppver.out prints positions to eight decimal places of a kilometer, so 1e-8
// km is the file's own resolution and nothing can agree better than that. Most
// of the suite sits there: 30 of the 31 comparable cases agree to 3e-8 km or
// better, which is ~1e-12 relative and is float64 accumulation over a few
// hundred chained operations.
//
// Two cases are larger, and the reason is conditioning rather than error.
// Satellite 23333 (WIND, e = 0.973) differs by 4.1e-6 km and 20413 (e = 0.786)
// by 4.8e-7. Both are worst at tsince = 0 and IMPROVE monotonically from there
// — 23333 falls from 4.1e-6 km to 8.0e-7 km by tsince 1600 — which rules out
// accumulation, and rules out the Kepler iteration degrading with time. Both
// are near perigee at epoch, where a highly eccentric orbit's position is most
// sensitive to the eccentric anomaly: the amplification is of order (1+e)/(1-e),
// which is 73 at e = 0.973. A one-ulp difference in the last bits of axnl and
// aynl arrives as micrometers of position there and nanometers at apogee.
//
// So the contract is set at 1e-4 km — 24x the measured maximum, which leaves
// room for fused multiply-add to move the last bits differently on ARM64, and
// four orders below the 1 km scale at which a disagreement would mean a
// different algorithm rather than a different rounding.
const valladoMaxKM = 1e-4

// valladoMaxKMPerSec is the same bound for velocity. The measured maximum is
// 1.9e-9 km/s.
const valladoMaxKMPerSec = 1e-7

// valladoP99KM is a regression detector rather than a contract. It has no
// physical justification, only a measured one: p99 was 9.8e-7 km when this was
// written, so this fails if the typical case degrades tenfold while still
// passing the contract.
const valladoP99KM = 1e-5

// artefactRows are reference rows that are not states.
//
// Satellite 33334 is one of the three element sets Vallado hand-built to drive
// SGP4 into an error return. Its block in tcppver.out has exactly one row, at
// tsince 0 — and that row is byte-for-byte identical to the LAST row of the
// preceding block, satellite 33333:
//
//	33333 xx
//	...
//	  20.00000000  23876.96955477  -37275.65263893  -8113.95104473  ...
//	33334 xx
//	   0.00000000  23876.96955477  -37275.65263893  -8113.95104473
//
// The propagator errored immediately on 33334 and wrote nothing, so the
// harness printed whatever was still in its output buffer. It is a stale
// buffer, not a state, and comparing against it would be comparing against
// another satellite.
//
// This implementation refuses 33334 at tsince 0 with ErrPerturbedEccentricity,
// which is the correct behavior and is asserted by
// TestValladosErrorCasesReachTheModel.
var artefactRows = map[string]bool{"33334": true}

// TestAgreesWithVallado is the measurement this package exists to make.
//
// # What a failure here means
//
// The reference states were generated by Vallado's own C++. A disagreement is
// this package's, and at this tolerance it is a specific line: the terms are
// evaluated in the reference's own association precisely so that a difference
// is a transcription error rather than a rounding difference nobody can locate.
func TestAgreesWithVallado(t *testing.T) {
	t.Parallel()

	sets := loadValladoTLEs(t)
	blocks := loadValladoReference(t)

	byNum := make(map[string][]valladoSet)
	for _, s := range sets {
		byNum[s.satnum] = append(byNum[s.satnum], s)
	}

	used := make(map[string]int)

	var (
		posErrors []float64
		velErrors []float64
		worst     = make(map[string]float64)
		deep      []string
		states    int
	)

	for _, blk := range blocks {
		idx := used[blk.satnum]
		used[blk.satnum]++

		candidates := byNum[blk.satnum]
		if idx >= len(candidates) {
			t.Errorf("satellite %s: reference has more blocks than the element file has sets", blk.satnum)

			continue
		}

		el, err := sgp4.ParseTLE(candidates[idx].line1, candidates[idx].line2)
		if err != nil {
			t.Errorf("satellite %s: ParseTLE: %v", blk.satnum, err)

			continue
		}

		p, err := sgp4.New(el)
		if err != nil {
			t.Errorf("satellite %s: New: %v", blk.satnum, err)

			continue
		}

		if p.DeepSpace() {
			deep = append(deep, blk.satnum)
		}

		if artefactRows[blk.satnum] {
			continue
		}

		for _, row := range blk.rows {
			pos, vel, err := p.At(row[0])
			if err != nil && !advisory(err) {
				// The reference prints a state for every row it lists, so a
				// hard error where it has an answer is a disagreement about
				// the model, not about a number.
				t.Errorf("satellite %s at tsince %g: %v", blk.satnum, row[0], err)

				continue
			}

			dp := norm3(pos.X, pos.Y, pos.Z, row[1], row[2], row[3])
			dv := norm3(vel.X, vel.Y, vel.Z, row[4], row[5], row[6])

			states++

			posErrors = append(posErrors, dp)
			velErrors = append(velErrors, dv)

			if dp > worst[blk.satnum] {
				worst[blk.satnum] = dp
			}

			if dp > valladoMaxKM {
				t.Errorf("satellite %s at tsince %g: position differs by %.6g km, contract is %.0e",
					blk.satnum, row[0], dp, valladoMaxKM)
			}

			if dv > valladoMaxKMPerSec {
				t.Errorf("satellite %s at tsince %g: velocity differs by %.6g km/s, contract is %.0e",
					blk.satnum, row[0], dv, valladoMaxKMPerSec)
			}
		}
	}

	sort.Strings(deep)
	sort.Float64s(posErrors)
	sort.Float64s(velErrors)

	if states == 0 {
		t.Fatal("no states were compared at all; the fixtures are not being read")
	}

	t.Logf("compared %d states across %d cases, %d of them deep space: %v",
		states, len(worst), len(deep), deep)
	t.Logf("position  p50=%.3g  p90=%.3g  p99=%.3g  max=%.3g km",
		quantile(posErrors, 0.5), quantile(posErrors, 0.9),
		quantile(posErrors, 0.99), quantile(posErrors, 1))
	t.Logf("velocity  p50=%.3g  max=%.3g km/s",
		quantile(velErrors, 0.5), quantile(velErrors, 1))

	type reported struct {
		num string
		km  float64
	}

	ranked := make([]reported, 0, len(worst))
	for num, km := range worst {
		ranked = append(ranked, reported{num, km})
	}

	sort.Slice(ranked, func(i, j int) bool { return ranked[i].km > ranked[j].km })

	for _, r := range ranked {
		t.Logf("  sat %-6s max %.6g km", r.num, r.km)
	}

	if p99 := quantile(posErrors, 0.99); p99 > valladoP99KM {
		t.Errorf("p99 position difference is %.3g km against a %.0e regression detector.\n"+
			"  Still inside the %.0e contract, so this is not yet a correctness failure — but "+
			"the typical case has moved by an order of magnitude and something changed.",
			p99, valladoP99KM, valladoMaxKM)
	}

	// The floor, from the other side: if agreement became perfect, the
	// comparison has stopped comparing — a fixture read as zeros, or a loop
	// that never ran. The reference prints to 1e-8 km, so a median of exactly
	// zero across hundreds of states is not a better implementation.
	if p50 := quantile(posErrors, 0.5); p50 == 0 {
		t.Error("the median position difference is exactly zero across every state, which the " +
			"reference file's own eight-decimal precision cannot produce; the comparison is " +
			"probably not comparing")
	}
}

// TestEveryDivergenceIsGone is the result this whole rewrite was for.
//
// astrogo's Vallado suite reported seven divergent cases against the Go
// implementation it depended on, from 0.22 km to 3438 km. TuSKan/astrogo#309
// traced six of them to one digit — 128 where the algorithm has 120, in the s⁴
// atmospheric-density coefficient that feeds the secular drag term — and
// expected the seventh, 23333, to survive, because its perigee is above the
// 156 km branch and Vallado annotates it as where the Spacetrack Report #3
// Kepler solver stops converging.
//
// It does not survive. 23333 agrees to 4.1e-6 km here, a factor of 53,000
// better than the implementation being replaced, and its Kepler iteration
// converges at every one of its fifteen states. Whatever the incumbent was
// doing on that case, it was not the documented limitation of the algorithm.
//
// The expectation was written down before it was measured, which is the only
// reason it can be reported as refuted rather than quietly adjusted.
func TestEveryDivergenceIsGone(t *testing.T) {
	t.Parallel()

	sets := loadValladoTLEs(t)
	blocks := loadValladoReference(t)

	byNum := make(map[string]valladoSet)
	for _, s := range sets {
		if _, seen := byNum[s.satnum]; !seen {
			byNum[s.satnum] = s
		}
	}

	// Every case astrogo could not reproduce, with the error it showed.
	for _, tc := range []struct {
		satnum      string
		incumbentKM float64
		what        string
	}{
		{"28350", 3438.51, "near-Earth, perigee 127 km — the low-perigee s4 modification"},
		{"22312", 1828.92, "SL-6 R/B(2), the last element set before it decayed in 2006"},
		{"16925", 1328.37, "deep space, the s4 > 20 modification"},
		{"11801", 781.71, "the original Spacetrack Report #3 deep-space case"},
		{"28623", 485.94, "H-2 R/B — deep space AND perigee 136 km, both s4 paths at once"},
		{"28872", 7.78, "perigee is negative (−51 km); lost within 50 minutes"},
		{"23333", 0.2175, "WIND, e = 0.973 — the case that was expected to survive"},
	} {
		s := byNum[tc.satnum]

		el, err := sgp4.ParseTLE(s.line1, s.line2)
		if err != nil {
			t.Fatalf("%s: %v", tc.satnum, err)
		}

		p, err := sgp4.New(el)
		if err != nil {
			t.Fatalf("%s: %v", tc.satnum, err)
		}

		var (
			found bool
			worst float64
		)

		for _, blk := range blocks {
			if blk.satnum != tc.satnum {
				continue
			}

			found = true

			for _, row := range blk.rows {
				pos, _, err := p.At(row[0])
				if err != nil && !advisory(err) {
					t.Errorf("%s at tsince %g: %v", tc.satnum, row[0], err)

					continue
				}

				if d := norm3(pos.X, pos.Y, pos.Z, row[1], row[2], row[3]); d > worst {
					worst = d
				}
			}
		}

		if !found {
			t.Fatalf("the reference file no longer carries satellite %s", tc.satnum)
		}

		if worst > valladoMaxKM {
			t.Errorf("satellite %s (%s) differs by %.6g km, contract %.0e — a divergence "+
				"#309 said would go away has not",
				tc.satnum, tc.what, worst, valladoMaxKM)

			continue
		}

		t.Logf("satellite %-6s %8.2f km with the incumbent -> %.3g km here (%s)",
			tc.satnum, tc.incumbentKM, worst, tc.what)
	}
}

// TestValladosErrorCasesReachTheModel is the payoff for separating checksum
// verification from parsing.
//
// Vallado hand-built 33333, 33334 and 33335 to drive SGP4 into three of its
// error returns, and never maintained their check digits. astrogo could not
// read them at all — a checksum-enforcing parser refuses all three — so its
// coverage of its own reference suite was 30 of 33 and the model's error paths
// were untested. They are testable now.
//
// What each one actually does, measured, against what Vallado wrote in the
// element file's own comments:
//
//   - 33333, "check error code 4": reaches a negative semi-latus rectum, which
//     is his error 4. Confirmed.
//   - 33334, "try and check error code 2 but this ...": his note breaks off
//     mid-sentence, and the measurement says why. It does not reach error 2 (a
//     non-positive mean motion); the lunisolar periodics drive the perturbed
//     eccentricity to −122 first, which is his error 3.
//   - 33335, "try to check error code 3 looks like ep never goes below zero":
//     he is right, and it raises nothing at all. Asserted as raising nothing,
//     so that a future change which starts erroring here is noticed.
func TestValladosErrorCasesReachTheModel(t *testing.T) {
	t.Parallel()

	sets := loadValladoTLEs(t)

	byNum := make(map[string]valladoSet)
	for _, s := range sets {
		if _, seen := byNum[s.satnum]; !seen {
			byNum[s.satnum] = s
		}
	}

	for _, tc := range []struct {
		satnum  string
		tsince  float64
		wantErr error
		note    string
	}{
		{"33333", 100, sgp4.ErrSemiLatusRectum, `"check error code 4"`},
		{"33334", 0, sgp4.ErrPerturbedEccentricity, `"try and check error code 2 but this ..."`},
		{"33334", 500, sgp4.ErrEccentricity, "and the mean eccentricity leaves range later"},
		{"33335", 1440, nil, `"looks like ep never goes below zero" — and it does not`},
	} {
		s, ok := byNum[tc.satnum]
		if !ok {
			t.Fatalf("the fixture no longer carries satellite %s", tc.satnum)
		}

		// The parser must read it. That is the whole point: these three carry
		// check digits that do not match, and they are perfectly good elements.
		el, err := sgp4.ParseTLE(s.line1, s.line2)
		if err != nil {
			t.Fatalf("%s: ParseTLE refused an element set whose only defect is its "+
				"check digit: %v", tc.satnum, err)
		}

		if cerr := sgp4.VerifyTLEChecksums(s.line1, s.line2); cerr == nil {
			t.Errorf("%s was expected to carry a bad check digit and does not; if the "+
				"fixture was regenerated this test's premise has changed", tc.satnum)
		}

		p, err := sgp4.New(el)
		if err != nil {
			t.Fatalf("%s: New: %v", tc.satnum, err)
		}

		_, _, err = p.At(tc.tsince)

		switch {
		case tc.wantErr == nil && err != nil:
			t.Errorf("%s at tsince %g raised %v, want none — %s", tc.satnum, tc.tsince, err, tc.note)
		case tc.wantErr != nil && !errors.Is(err, tc.wantErr):
			t.Errorf("%s at tsince %g raised %v, want one wrapping %v — %s",
				tc.satnum, tc.tsince, err, tc.wantErr, tc.note)
		}
	}
}

// TestLowPerigeeCasesAreTheOnesThatMatter names the element sets that exercise
// the s⁴ drag alteration, so that a regression there is reported as itself.
//
// These are the cases the Go implementation astrogo used before this one gets
// wrong — by up to 3438 km — because it has 128 where the algorithm has 120 in
// the density coefficient (TuSKan/astrogo#309). They are near-Earth, so they
// are covered by this step rather than the next, and they are the whole reason
// the build was split here.
func TestLowPerigeeCasesAreTheOnesThatMatter(t *testing.T) {
	t.Parallel()

	sets := loadValladoTLEs(t)

	byNum := make(map[string]valladoSet)
	for _, s := range sets {
		if _, seen := byNum[s.satnum]; !seen {
			byNum[s.satnum] = s
		}
	}

	// Perigee altitudes from Vallado's own comments in the element file, where
	// he wrote them; the rest measured.
	for _, tc := range []struct {
		satnum     string
		wantPerige float64
		tol        float64
		note       string
	}{
		{"28350", 127.20, 0.05, `"Near Earth, perigee = 127.20 (< 156) s4 mod"`},
		{"28872", -51.00, 1.00, `"(perigee = -51km), lost in 50 minutes"`},
		{"22312", 79.39, 0.05, "SL-6 R/B(2), the last set before it decayed"},
	} {
		s, ok := byNum[tc.satnum]
		if !ok {
			t.Fatalf("the fixture no longer carries satellite %s", tc.satnum)
		}

		el, err := sgp4.ParseTLE(s.line1, s.line2)
		if err != nil {
			t.Fatalf("%s: %v", tc.satnum, err)
		}

		p, err := sgp4.New(el)
		if err != nil {
			t.Fatalf("%s: %v", tc.satnum, err)
		}

		if got := p.PerigeeAltitude(); math.Abs(got-tc.wantPerige) > tc.tol {
			t.Errorf("satellite %s: perigee %.2f km, want %.2f — %s.\n"+
				"  A gap near 1.4 km means the Kozai correction is missing and this is the "+
				"two-body value, which is not the number SGP4 branches on.",
				tc.satnum, got, tc.wantPerige, tc.note)
		}

		if !p.SimplifiedDrag() {
			t.Errorf("satellite %s has a perigee of %.1f km and does not take the simplified "+
				"drag branch", tc.satnum, p.PerigeeAltitude())
		}
	}
}

// TestPropagatorIsSafeToShare asserts the claim Propagator's doc comment makes,
// under the race detector.
//
// It is not a formality. The reference implementation threads its state through
// a mutable record and mutates it on every evaluation, so the obvious
// transcription of this model is not safe to call twice at once — and a caller
// propagating a catalogue across a time grid will do exactly that.
func TestPropagatorIsSafeToShare(t *testing.T) {
	t.Parallel()

	el, err := sgp4.ParseTLE(issLine1, issLine2)
	if err != nil {
		t.Fatal(err)
	}

	p, err := sgp4.New(el)
	if err != nil {
		t.Fatal(err)
	}

	const (
		goroutines = 8
		steps      = 200
	)

	serial := make([]float64, steps)

	for i := range steps {
		pos, _, err := p.At(float64(i) * 7.5)
		if err != nil {
			t.Fatalf("serial at step %d: %v", i, err)
		}

		serial[i] = pos.X
	}

	results := make([][]float64, goroutines)
	done := make(chan int, goroutines)

	for g := range goroutines {
		results[g] = make([]float64, steps)

		go func(g int) {
			for i := range steps {
				pos, _, _ := p.At(float64(i) * 7.5)
				results[g][i] = pos.X
			}

			done <- g
		}(g)
	}

	for range goroutines {
		<-done
	}

	for g := range goroutines {
		for i := range steps {
			if results[g][i] != serial[i] {
				t.Fatalf("goroutine %d step %d produced %.17g, serial produced %.17g — "+
					"the propagator is carrying state between calls",
					g, i, results[g][i], serial[i])
			}
		}
	}
}

// TestResonantOrbitIsOrderIndependent is the claim that let the resonance
// integrator be made pure, tested directly rather than argued.
//
// Vallado's dspace carries atime, xli and xni between calls so a forward march
// does not redo its 720-minute steps. This package restarts from zero every
// call, on the reasoning that the grid is anchored at t = 0 and the step is
// fixed, so resuming and restarting land on the same points.
//
// If that reasoning were wrong the symptom would be order dependence: a state
// computed after a long forward march would differ from the same state computed
// cold. This walks a resonant orbit forwards, then backwards, then jumps around
// at random, and requires every value to be bit-identical to the cold one.
//
// Satellite 23333 is used because it is resonant AND eccentric, so it exercises
// the integrator over many steps with the worst conditioning in the suite.
func TestResonantOrbitIsOrderIndependent(t *testing.T) {
	t.Parallel()

	sets := loadValladoTLEs(t)

	var pick valladoSet

	for _, s := range sets {
		if s.satnum == "23333" {
			pick = s

			break
		}
	}

	el, err := sgp4.ParseTLE(pick.line1, pick.line2)
	if err != nil {
		t.Fatal(err)
	}

	p, err := sgp4.New(el)
	if err != nil {
		t.Fatal(err)
	}

	if !p.DeepSpace() {
		t.Fatal("satellite 23333 is not being treated as deep space")
	}

	// Times spanning several integrator steps in both directions.
	times := []float64{0, 720, 1440, 2160, 2880, 5760, -720, -2880}

	cold := make([]float64, len(times))

	for i, ts := range times {
		// A fresh propagator per point: no prior call of any kind.
		fresh, ferr := sgp4.New(el)
		if ferr != nil {
			t.Fatal(ferr)
		}

		pos, _, _ := fresh.At(ts)
		cold[i] = pos.X
	}

	// Now the same points out of a single propagator, in three awkward orders.
	for _, order := range [][]int{
		{0, 1, 2, 3, 4, 5, 6, 7},
		{7, 6, 5, 4, 3, 2, 1, 0},
		{4, 0, 7, 2, 5, 1, 6, 3},
	} {
		for _, i := range order {
			pos, _, _ := p.At(times[i])
			if pos.X != cold[i] {
				t.Fatalf("tsince %g gave %.17g after a different call order, and %.17g cold — "+
					"the resonance integrator is carrying state between calls",
					times[i], pos.X, cold[i])
			}
		}
	}
}

// TestAtIsAllocationFree pins the performance claim as a behavior rather than
// a benchmark number, so it runs in ordinary CI and blocks a merge.
func TestAtIsAllocationFree(t *testing.T) {
	el, err := sgp4.ParseTLE(issLine1, issLine2)
	if err != nil {
		t.Fatal(err)
	}

	p, err := sgp4.New(el)
	if err != nil {
		t.Fatal(err)
	}

	tsince := 0.0

	allocs := testing.AllocsPerRun(1000, func() {
		tsince += 1.0
		_, _, _ = p.At(tsince)
	})

	if allocs != 0 {
		t.Errorf("At allocates %v times per call; propagating a catalogue across a time grid "+
			"is the whole workload and it should touch the heap never", allocs)
	}
}

// advisory reports whether err is one of the two the model raises alongside a
// state it did compute. Everywhere the reference prints a row, one of those is
// a disagreement about trust and not about arithmetic, so the comparison still
// runs.
func advisory(err error) bool {
	return errors.Is(err, sgp4.ErrDecayed) || errors.Is(err, sgp4.ErrKeplerNotConverged)
}

type refBlock struct {
	satnum string
	rows   [][7]float64 // tsince, x, y, z, vx, vy, vz
}

func loadValladoReference(t *testing.T) []refBlock {
	t.Helper()

	f, err := os.Open("../testdata/vallado/tcppver.out")
	if err != nil {
		t.Fatalf("open the reference states: %v", err)
	}

	defer func() { _ = f.Close() }()

	var (
		blocks []refBlock
		cur    *refBlock
	)

	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" {
			continue
		}

		if num, isHeader := strings.CutSuffix(line, " xx"); isHeader {
			blocks = append(blocks, refBlock{satnum: strings.TrimSpace(num)})
			cur = &blocks[len(blocks)-1]

			continue
		}

		if cur == nil {
			continue
		}

		fields := strings.Fields(line)
		if len(fields) < 7 {
			continue
		}

		var (
			row [7]float64
			ok  = true
		)

		for i := range row {
			v, perr := strconv.ParseFloat(fields[i], 64)
			if perr != nil {
				ok = false

				break
			}

			row[i] = v
		}

		if ok {
			cur.rows = append(cur.rows, row)
		}
	}

	if err := sc.Err(); err != nil {
		t.Fatalf("read the reference states: %v", err)
	}

	return blocks
}

func norm3(ax, ay, az, bx, by, bz float64) float64 {
	dx, dy, dz := ax-bx, ay-by, az-bz

	return math.Sqrt(dx*dx + dy*dy + dz*dz)
}

// quantile reads p of a sorted slice by nearest rank.
func quantile(sorted []float64, p float64) float64 {
	if len(sorted) == 0 {
		return 0
	}

	idx := min(max(int(p*float64(len(sorted)-1)), 0), len(sorted)-1)

	return sorted[idx]
}
