package sgp4_test

import (
	"bufio"
	"errors"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/TuSKan/astrogo/ephemeris/satellite/sgp4"
)

// This file measures the model against the reference states Vallado published
// with AIAA 2006-6753. See ../testdata/vallado/README.md for provenance.
//
// It is untagged, unlike astrogo's other validation suites, and deliberately:
// the fixture is 30 KB on disk, the comparison is a few hundred thousand
// floating-point operations, and there is no network and no external service
// anywhere in it. A correctness claim this cheap to check should be checked on
// every run.

// nearEarthMaxKM is the contract for the cases this step covers.
//
// One millimetre. That is not a statement about where satellites are — SGP4's
// own model error is kilometres within days of epoch — it is a statement about
// whether this is the same arithmetic as the reference.
//
// The reference file prints positions with eight decimal places of a kilometre,
// so 1e-8 km is its own resolution and no implementation can agree better than
// that. A faithful transcription given the same floating-point inputs should
// land within two or three orders of it; anything larger is a transcription
// difference, not rounding, and is worth finding rather than accommodating.
const nearEarthMaxKM = 1e-6

// nearEarthMaxKMPerSec is the same bound for velocity, scaled by the ratio the
// two quantities actually have in these orbits (roughly 7 km/s against 7000 km,
// so a thousandth).
const nearEarthMaxKMPerSec = 1e-9

// TestAgreesWithValladoNearEarth is the measurement this step exists to make.
//
// # What a failure here means
//
// The reference states were generated by Vallado's own C++. A disagreement is
// this package's, and at this tolerance it is a specific line: the terms are
// evaluated in the reference's own association precisely so that a difference
// is a transcription error rather than a rounding difference nobody can locate.
func TestAgreesWithValladoNearEarth(t *testing.T) {
	t.Parallel()

	sets := loadValladoTLEs(t)
	blocks := loadValladoReference(t)

	byNum := make(map[string][]valladoSet)
	for _, s := range sets {
		byNum[s.satnum] = append(byNum[s.satnum], s)
	}

	used := make(map[string]int)

	var (
		posErrors []float64
		velErrors []float64
		worst     = make(map[string]float64)
		deepSkip  []string
		states    int
	)

	for _, blk := range blocks {
		idx := used[blk.satnum]
		used[blk.satnum]++

		candidates := byNum[blk.satnum]
		if idx >= len(candidates) {
			t.Errorf("satellite %s: reference has more blocks than the element file has sets", blk.satnum)

			continue
		}

		el, err := sgp4.ParseTLE(candidates[idx].line1, candidates[idx].line2)
		if err != nil {
			t.Errorf("satellite %s: ParseTLE: %v", blk.satnum, err)

			continue
		}

		p, err := sgp4.New(el)
		if err != nil {
			// Deep space is the next step of the build. Recorded by name
			// rather than skipped silently, so the count is visible and the
			// list shrinks to nothing when SDP4 lands.
			if errors.Is(err, sgp4.ErrDeepSpace) {
				deepSkip = append(deepSkip, blk.satnum)

				continue
			}

			t.Errorf("satellite %s: New: %v", blk.satnum, err)

			continue
		}

		for _, row := range blk.rows {
			pos, vel, err := p.At(row[0])
			if err != nil && !errors.Is(err, sgp4.ErrDecayed) && !errors.Is(err, sgp4.ErrKeplerNotConverged) {
				// The reference prints a state for every row it lists, so a
				// hard error where it has an answer is a disagreement about
				// the model, not about a number.
				t.Errorf("satellite %s at tsince %g: %v", blk.satnum, row[0], err)

				continue
			}

			dp := norm3(pos.X, pos.Y, pos.Z, row[1], row[2], row[3])
			dv := norm3(vel.X, vel.Y, vel.Z, row[4], row[5], row[6])

			states++

			posErrors = append(posErrors, dp)
			velErrors = append(velErrors, dv)

			if dp > worst[blk.satnum] {
				worst[blk.satnum] = dp
			}

			if dp > nearEarthMaxKM {
				t.Errorf("satellite %s at tsince %g: position differs by %.6g km, contract is %.0e",
					blk.satnum, row[0], dp, nearEarthMaxKM)
			}

			if dv > nearEarthMaxKMPerSec {
				t.Errorf("satellite %s at tsince %g: velocity differs by %.6g km/s, contract is %.0e",
					blk.satnum, row[0], dv, nearEarthMaxKMPerSec)
			}
		}
	}

	sort.Strings(deepSkip)
	sort.Float64s(posErrors)
	sort.Float64s(velErrors)

	if states == 0 {
		t.Fatal("no states were compared at all; the fixtures are not being read")
	}

	t.Logf("compared %d states across %d near-Earth cases; %d deep-space cases deferred: %v",
		states, len(worst), len(deepSkip), deepSkip)
	t.Logf("position  p50=%.3g  p90=%.3g  p99=%.3g  max=%.3g km",
		quantile(posErrors, 0.5), quantile(posErrors, 0.9),
		quantile(posErrors, 0.99), quantile(posErrors, 1))
	t.Logf("velocity  p50=%.3g  max=%.3g km/s",
		quantile(velErrors, 0.5), quantile(velErrors, 1))

	type reported struct {
		num string
		km  float64
	}

	ranked := make([]reported, 0, len(worst))
	for num, km := range worst {
		ranked = append(ranked, reported{num, km})
	}

	sort.Slice(ranked, func(i, j int) bool { return ranked[i].km > ranked[j].km })

	for _, r := range ranked {
		t.Logf("  sat %-6s max %.6g km", r.num, r.km)
	}

	if p99 := quantile(posErrors, 0.99); p99 > nearEarthP99KM {
		t.Errorf("p99 position difference is %.3g km against a %.0e regression detector.\n"+
			"  Still inside the %.0e contract, so this is not yet a correctness failure — but "+
			"the typical case has moved by an order of magnitude and something changed.",
			p99, nearEarthP99KM, nearEarthMaxKM)
	}

	// The floor, from the other side: if agreement became perfect, the
	// comparison has stopped comparing — a fixture read as zeros, or a loop
	// that never ran. The reference prints to 1e-8 km, so a median of exactly
	// zero across hundreds of states is not a better implementation.
	if p50 := quantile(posErrors, 0.5); p50 == 0 {
		t.Error("the median position difference is exactly zero across every state, which the " +
			"reference file's own eight-decimal precision cannot produce; the comparison is " +
			"probably not comparing")
	}
}

// nearEarthP99KM is a regression detector rather than a contract.
//
// It has no physical justification, only a measured one: p99 was 7.3e-9 km when
// this was written and the maximum 9.1e-9, so this fails if the typical case
// degrades by an order of magnitude while still passing the contract. The gap
// between the two numbers is deliberate — fused multiply-add is permitted on
// some platforms and not others, and the last bits of a few hundred chained
// operations are allowed to move a little between them.
const nearEarthP99KM = 1e-7

// TestTheS4DivergencesAreGone is the measurement TuSKan/astrogo#309 predicted,
// made against the implementation rather than against a patched dependency.
//
// astrogo's Vallado suite has been reporting seven divergent cases, and #309
// traced six of them to one digit in the Go implementation astrogo depends on:
// 128 where the algorithm has 120, in the s⁴ atmospheric-density coefficient
// that feeds the secular drag term. Three of those six are near-Earth and so
// are covered by this step; the others are deep space and follow.
//
// The prediction was that a faithful implementation makes them disappear. The
// numbers on the right are what this package actually produces.
func TestTheS4DivergencesAreGone(t *testing.T) {
	t.Parallel()

	sets := loadValladoTLEs(t)
	blocks := loadValladoReference(t)

	byNum := make(map[string]valladoSet)
	for _, s := range sets {
		if _, seen := byNum[s.satnum]; !seen {
			byNum[s.satnum] = s
		}
	}

	// The error the incumbent shows on each, from astrogo's own measurement.
	for _, tc := range []struct {
		satnum      string
		incumbentKM float64
		what        string
	}{
		{"28350", 3438.51, "near-Earth, perigee 127 km — the low-perigee s4 modification"},
		{"22312", 1828.92, "SL-6 R/B(2), the last element set before it decayed in 2006"},
		{"28872", 7.78, "perigee is negative (−51 km); lost within 50 minutes"},
	} {
		s := byNum[tc.satnum]

		el, err := sgp4.ParseTLE(s.line1, s.line2)
		if err != nil {
			t.Fatalf("%s: %v", tc.satnum, err)
		}

		p, err := sgp4.New(el)
		if err != nil {
			t.Fatalf("%s: %v", tc.satnum, err)
		}

		var found bool

		worst := 0.0

		for _, blk := range blocks {
			if blk.satnum != tc.satnum {
				continue
			}

			found = true

			for _, row := range blk.rows {
				pos, _, err := p.At(row[0])
				if err != nil && !errors.Is(err, sgp4.ErrDecayed) &&
					!errors.Is(err, sgp4.ErrKeplerNotConverged) {
					t.Errorf("%s at tsince %g: %v", tc.satnum, row[0], err)

					continue
				}

				if d := norm3(pos.X, pos.Y, pos.Z, row[1], row[2], row[3]); d > worst {
					worst = d
				}
			}
		}

		if !found {
			t.Fatalf("the reference file no longer carries satellite %s", tc.satnum)
		}

		if worst > nearEarthMaxKM {
			t.Errorf("satellite %s (%s) differs by %.6g km, contract %.0e — the divergence "+
				"#309 attributes to the s4 coefficient has NOT gone away, so either that "+
				"diagnosis or this transcription is wrong",
				tc.satnum, tc.what, worst, nearEarthMaxKM)

			continue
		}

		t.Logf("satellite %-6s %8.2f km with the incumbent -> %.3g km here (%s)",
			tc.satnum, tc.incumbentKM, worst, tc.what)
	}
}

// TestLowPerigeeCasesAreTheOnesThatMatter names the element sets that exercise
// the s⁴ drag alteration, so that a regression there is reported as itself.
//
// These are the cases the Go implementation astrogo used before this one gets
// wrong — by up to 3438 km — because it has 128 where the algorithm has 120 in
// the density coefficient (TuSKan/astrogo#309). They are near-Earth, so they
// are covered by this step rather than the next, and they are the whole reason
// the build was split here.
func TestLowPerigeeCasesAreTheOnesThatMatter(t *testing.T) {
	t.Parallel()

	sets := loadValladoTLEs(t)

	byNum := make(map[string]valladoSet)
	for _, s := range sets {
		if _, seen := byNum[s.satnum]; !seen {
			byNum[s.satnum] = s
		}
	}

	// Perigee altitudes from Vallado's own comments in the element file, where
	// he wrote them; the rest measured.
	for _, tc := range []struct {
		satnum     string
		wantPerige float64
		tol        float64
		note       string
	}{
		{"28350", 127.20, 0.05, `"Near Earth, perigee = 127.20 (< 156) s4 mod"`},
		{"28872", -51.00, 1.00, `"(perigee = -51km), lost in 50 minutes"`},
		{"22312", 79.39, 0.05, "SL-6 R/B(2), the last set before it decayed"},
	} {
		s, ok := byNum[tc.satnum]
		if !ok {
			t.Fatalf("the fixture no longer carries satellite %s", tc.satnum)
		}

		el, err := sgp4.ParseTLE(s.line1, s.line2)
		if err != nil {
			t.Fatalf("%s: %v", tc.satnum, err)
		}

		p, err := sgp4.New(el)
		if err != nil {
			t.Fatalf("%s: %v", tc.satnum, err)
		}

		if got := p.PerigeeAltitude(); math.Abs(got-tc.wantPerige) > tc.tol {
			t.Errorf("satellite %s: perigee %.2f km, want %.2f — %s.\n"+
				"  A gap near 1.4 km means the Kozai correction is missing and this is the "+
				"two-body value, which is not the number SGP4 branches on.",
				tc.satnum, got, tc.wantPerige, tc.note)
		}

		if !p.SimplifiedDrag() {
			t.Errorf("satellite %s has a perigee of %.1f km and does not take the simplified "+
				"drag branch", tc.satnum, p.PerigeeAltitude())
		}
	}
}

// TestPropagatorIsSafeToShare asserts the claim Propagator's doc comment makes,
// under the race detector.
//
// It is not a formality. The reference implementation threads its state through
// a mutable record and mutates it on every evaluation, so the obvious
// transcription of this model is not safe to call twice at once — and a caller
// propagating a catalogue across a time grid will do exactly that.
func TestPropagatorIsSafeToShare(t *testing.T) {
	t.Parallel()

	el, err := sgp4.ParseTLE(issLine1, issLine2)
	if err != nil {
		t.Fatal(err)
	}

	p, err := sgp4.New(el)
	if err != nil {
		t.Fatal(err)
	}

	const (
		goroutines = 8
		steps      = 200
	)

	serial := make([]float64, steps)

	for i := range steps {
		pos, _, err := p.At(float64(i) * 7.5)
		if err != nil {
			t.Fatalf("serial at step %d: %v", i, err)
		}

		serial[i] = pos.X
	}

	results := make([][]float64, goroutines)
	done := make(chan int, goroutines)

	for g := range goroutines {
		results[g] = make([]float64, steps)

		go func(g int) {
			for i := range steps {
				pos, _, _ := p.At(float64(i) * 7.5)
				results[g][i] = pos.X
			}

			done <- g
		}(g)
	}

	for range goroutines {
		<-done
	}

	for g := range goroutines {
		for i := range steps {
			if results[g][i] != serial[i] {
				t.Fatalf("goroutine %d step %d produced %.17g, serial produced %.17g — "+
					"the propagator is carrying state between calls",
					g, i, results[g][i], serial[i])
			}
		}
	}
}

// TestAtIsAllocationFree pins the performance claim as a behaviour rather than
// a benchmark number, so it runs in ordinary CI and blocks a merge.
func TestAtIsAllocationFree(t *testing.T) {
	el, err := sgp4.ParseTLE(issLine1, issLine2)
	if err != nil {
		t.Fatal(err)
	}

	p, err := sgp4.New(el)
	if err != nil {
		t.Fatal(err)
	}

	tsince := 0.0

	allocs := testing.AllocsPerRun(1000, func() {
		tsince += 1.0
		_, _, _ = p.At(tsince)
	})

	if allocs != 0 {
		t.Errorf("At allocates %v times per call; propagating a catalogue across a time grid "+
			"is the whole workload and it should touch the heap never", allocs)
	}
}

type refBlock struct {
	satnum string
	rows   [][7]float64 // tsince, x, y, z, vx, vy, vz
}

func loadValladoReference(t *testing.T) []refBlock {
	t.Helper()

	f, err := os.Open("../testdata/vallado/tcppver.out")
	if err != nil {
		t.Fatalf("open the reference states: %v", err)
	}

	defer func() { _ = f.Close() }()

	var (
		blocks []refBlock
		cur    *refBlock
	)

	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" {
			continue
		}

		if num, isHeader := strings.CutSuffix(line, " xx"); isHeader {
			blocks = append(blocks, refBlock{satnum: strings.TrimSpace(num)})
			cur = &blocks[len(blocks)-1]

			continue
		}

		if cur == nil {
			continue
		}

		fields := strings.Fields(line)
		if len(fields) < 7 {
			continue
		}

		var (
			row [7]float64
			ok  = true
		)

		for i := range row {
			v, perr := strconv.ParseFloat(fields[i], 64)
			if perr != nil {
				ok = false

				break
			}

			row[i] = v
		}

		if ok {
			cur.rows = append(cur.rows, row)
		}
	}

	if err := sc.Err(); err != nil {
		t.Fatalf("read the reference states: %v", err)
	}

	return blocks
}

func norm3(ax, ay, az, bx, by, bz float64) float64 {
	dx, dy, dz := ax-bx, ay-by, az-bz

	return math.Sqrt(dx*dx + dy*dy + dz*dz)
}

// quantile reads p of a sorted slice by nearest rank.
func quantile(sorted []float64, p float64) float64 {
	if len(sorted) == 0 {
		return 0
	}

	idx := min(max(int(p*float64(len(sorted)-1)), 0), len(sorted)-1)

	return sorted[idx]
}
